#!/bin/sh
set -e
set -x

DOTFILES_DIR=`dirname $0`
cd $DOTFILES_DIR
DOTFILES_DIR=$(pwd)
cd -
INST_ZSHRC=~/.zshrc
INST_TMUX_DIR=~/.tmux
INST_TMUX_CONF=~/.tmux.conf
CTAGS_CONF=.ctags
NVIM_CONF=.config/nvim

if [ ! -e $INST_TMUX_DIR ]; then
    ln -s $DOTFILES_DIR/.tmux $INST_TMUX_DIR
fi

if [ ! -e $INST_TMUX_CONF ]; then
    ln -s $INST_TMUX_DIR/.tmux.conf $INST_TMUX_CONF
fi

if [ ! -e ~/$CTAGS_CONF ]; then
    ln -s $DOTFILES_DIR/$CTAGS_CONF ~/$CTAGS_CONF
fi

if [ ! -e ~/$NVIM_CONF ]; then
    ln -s $DOTFILES_DIR/$NVIM_CONF ~/$NVIM_CONF
fi

CURR_SHELL=$SHELL
ZSH_PATH=`which zsh`
if [ "$?" -eq "0" ]; then
    if [ ! -d ~/.oh-my-zsh ]; then
        git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    fi

    if [ ! -e $INST_ZSHRC ]; then
        ln -s $DOTFILES_DIR/.zshrc $INST_ZSHRC
    fi

    if [ ! "${CURR_SHELL#-}" = "$ZSH_PATH" ]; then
        chsh -s "$ZSH_PATH"
    fi
fi
