#!/bin/sh
set -e
set -x

git subtree pull \
    --prefix .vim/bundle/Vundle.vim \
    https://github.com/VundleVim/Vundle.vim.git master

git subtree pull \
    --prefix .tmux \
    https://github.com/tony/tmux-config.git master

git submodule init
git submodule update

vim +PluginUpdate +qall
